### ISSUE TITLE
Publish on AUR?

### ISSUE THREAD

**Issue by ReekyMarko** [varmd/wine-wayland#1]
You already have a PKGBUILD, so I suggest you publish this in the AUR. Would make installing (and updating) a lot easier. You can start with -git packages if you don't want to start tagging releases yet.

I have some experience on maintaining AUR packages. Hit me up if you need any help.

**Comment by appetrosyan** [comment]
I second that.

**Comment by varmd** [comment]
No interest in AUR, but if someone else is interested they can publish it there.
