### ISSUE TITLE
Window fails to close when the application exits

### ISSUE THREAD

**Issue by ComfyKernel** [varmd/wine-wayland#11]
Did some testing with unity games (Muse Dash in particular).

Whenever the game crashed or failed to open, the vulkan window remained on screen. This isn't the case for normal wine apps such as winecfg, but it seems to affect this game in particular.

Extra note: is it possible to run steam on wine-vulkan, or use the patch with steam instead of proton? Because if that is possible I will try this out on a lot of other games, and Muse Dash doesn't really get that far without steam running

OS : Arch Linux, Kernel 5.8
**Driver** : Intel Iris / i965 / i915 (Really confusing, but they're all the same driver in this case, but sometimes they aren't?)
**Graphics**: Intel IvyBridge, name unknown since lenovo's bios makes things hard
Device : Lenovo Thinkpad x230t

**Comment by varmd** [comment]
That is normal if a game hangs or crashes. 

For Steam, it maybe possible to replace proton folder, but it makes no sense since Steam uses X11. Might as well use regular Proton.

However, for just downloading games from Steam you can use steamctl - https://github.com/ValvePython/steamctl.

**Comment by ComfyKernel** [comment]
Is it possible to have the steam client running in some sort?

In this case the games I'm trying exit out or refuse to load without it active

**Comment by varmd** [comment]
Not until the Steam Big Picture mode shows text content in Wine.
