### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by ChazyTheBest** [varmd/wine-wayland#12]
I have followed the install instructions, installed a dependency I didn't have (vulkan-headers) and then just run `makepkg`.

The only change I made to the PKGBUILD file was to change the number of threads: `-j 16` (instead of 5).

Configure runs fine but I'm getting errors in the build process. You can see the errors from line [1785](https://gist.github.com/ChazyTheBest/01da0c4135fc1f23756724333a72e46d#file-gistfile1-txt-L1785) onwards. The rest (beginning) of the log is irrelevant but I can include it.

**Comment by varmd** [comment]
Are you using GCC10 and Archlinux/Manjaro? Try redownloading the package from github.

**Comment by ChazyTheBest** [comment]
Ok, it looks like Arch linux's makepkg by default uses clang?

Would you mind specifying `gcc` and `g++` in the README.md?
