### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by toby63** [varmd/wine-wayland#14]
When I try to build your package I see the following warnings in the console:
```
MinGW compiler not found, cross-compiling PE files won't be supported.
configure: gstreamer-1.0 base plugins 64-bit development files not found, GStreamer won't be supported.
configure: OSS sound system found but too old (OSSv4 needed), OSS won't be supported.
configure: WARNING: libxslt 64-bit development files not found, xslt won't be supported.
```

While `OSS` is not necessary (because mostly `pulseaudio` will be used), the others are at least useful:
- `Gstreamer` is used for playing videos and audio in Games
- `xstl` is used for XML parsing

I solved this by installing the following packages:
```
gst-plugins-base (for 32bit: lib32-gst-plugins-base)
libxslt (for 32bit: lib32-libxslt)

#From AUR:
mingw-w64-gcc-bin 
#and dependencies:
mingw-w64-binutils-bin
mingw-w64-headers-bin
mingw-w64-winpthreads-bin
mingw-w64-crt-bin
```

**Comment by toby63** [comment]
I also notice missing dependencies for 32-bit:
```
configure: OpenCL 32-bit development files not found, OpenCL won't be supported.
configure: libgnutls 32-bit development files too old, bcrypt encryption won't be supported.
configure: libv4l2 32-bit development files not found.
configure: libpulse 32-bit development files not found or too old, Pulse won't be supported.
configure: OSS sound system found but too old (OSSv4 needed), OSS won't be supported.
configure: libudev 32-bit development files not found, plug and play won't be supported.
configure: libcapi20 32-bit development files not found, ISDN won't be supported.
configure: libkrb5 32-bit development files not found (or too old), Kerberos won't be supported.
configure: libtiff 32-bit development files not found, TIFF won't be supported.
configure: libopenal 32-bit development files not found (or too old),

configure: WARNING: libgnutls 32-bit development files not found, no schannel support.

```

Partly this can be solved by installing:
lib32-gnutls
lib32-v4l-utils
lib32-libpulse
lib32-krb5
lib32-libtiff
(for libudev install: systemd-libs)

We can probably ignore OSS (optional audio), libcapi (isdn) and also openal & opencl.
Regarding `udev` I assume it is also not intended to be included (because it is disabled in the 64-bit version).

---

Maybe you could edit the PKGBUILD files so they fit each other and explain a bit, why what is needed or not needed.

**Comment by varmd** [comment]
These are just warnings, not errors.

Most games work fine without gstreamer, so it shouldn't be a hard requirement.

Gstreamer maybe necessary for mfplat and WMV/MP4 content. However, gstreamer on Archlinux requires X11 packages, and additionally it's not clear if it works on Wayland. If there are reports of it and mfplat working on Wayland with WMV/MP4 content I'll add a note to the README about installing gstreamer.

Not aware of anything that may need Mingw and xslt and all the games I've tested did not require them.

Regarding lib32* packages, most 32bit games are offline these days, and users shouldn't have to install these packages to run their offline 32bit games.

**Comment by toby63** [comment]
The packages could be mentioned as optional.
So users who need those can install them.

> However, gstreamer on Archlinux requires X11 packages, and additionally it's not clear if it works on Wayland. If there are reports of it and mfplat working on Wayland with WMV/MP4 content I'll add a note to the README about installing gstreamer.

:thinking: I will try to find some software to test it with. 
In general I only found this so far: https://gstreamer.freedesktop.org/documentation/waylandsink/index.html?gi-language=c
which seems to imply that gstreamer works on wayland, but I don't know about the wine implementation and different video formats.

> Regarding lib32* packages, most 32bit games are offline these days, and users shouldn't have to install these packages to run their offline 32bit games.

I don't think thats true, many people still play older games in multiplayer.
