### ISSUE TITLE
[Questions] folders in start-example.sh & dxvk

### ISSUE THREAD

**Issue by toby63** [varmd/wine-wayland#17]
1. Is there a specific reason why the Gamefolder needs to be exactly in this place `"prefix/$FOLDER1/$FOLDER2"` ?

---

2. Regarding DXVK:
    While trying to install dxvk with the usual official method:
    ```
    export WINEPREFIX=/path/to/.wine-prefix
    ./setup_dxvk.sh install
    ```
    I noticed that it reports missing files.

Your readme describes:
`Copy relevant 64bit or 32bit dxvk dlls to prefix/your-game or use winetricks.`

Does this just mean technically the same as above (copying it into the virtual windows folders), or does your version of wine somehow use the dxvk-files from the folder `prefix/your-game`?

---

You could also add a bit more explaination about:

- `export RADV_PERFTEST=aco`  - seems to be only for some special amd cards
- `#dxvk options here` - I see no .conf file, so it's empty I assume?

- `WINEDLLOVERRIDES="dxgi,d3d11=n,b;dinput=d;winedbg=d;winemenubuilder.exe=d;mscoree=d;mshtml=d"` - what does n,b,d mean and why are specific things disabled etc.?

**Comment by varmd** [comment]
1. This is necessary for the script to work as is.
2. dxvk installation is described in the readme - e.g copying dll files to game directory or windows/system32. 
I've also added the wineland launcher which installs dxvk automatically and may remove the start-example.sh in the future to avoid confusion
