### ISSUE TITLE
Add "provides wine" to PKGBUILD?

### ISSUE THREAD

**Issue by toby63** [varmd/wine-wayland#20]
Some packages like "winetricks" for example have "wine" as dependency.

It would be convenient if wine-wayland would be seen as sufficient by pacman.

**Comment by Mel34** [comment]
wine-nine is also complaining about wine not being installed

**Comment by toby63** [comment]
@Mel34 I doubt that this version is running with wine-nine.
As the readme this is for use with proton, so dx9,10 & 11 are "translated" with the help of dxvk.
Wine-nine is the version for using the gallium-nine driver of mesa, which uses dx9 directly.

**Comment by Mel34** [comment]
I was referring to the way wine-nine is packaged, it's got a wine dependency on arch which the provided package in this repo doesn't cover.

**Comment by varmd** [comment]
Added. 

gallium-nine requires x11.
