### ISSUE TITLE
Question on graphic driver implementation i.e. winewayland.drv

### ISSUE THREAD

**Issue by StarAurryon** [varmd/wine-wayland#22]
Hello Varmd,

I am currently trying to port wine graphic stack to SDL2 as it is supported by X11 and Wayland (that is currently my second attempt).
Do you have some hints on how I could get the surface buffer from wine and what are the key functions to implement to have a proper winecfg dialog as a start. I am struggling to find documentation and encountering some segfaults, wine freeze, etc.

Thanks in advance,

Aurryon

**Comment by varmd** [comment]
For the GDI buffer source, you can take a look at WAYLANDDRV_WindowPosChanging and android_surface_flush in winewayland.drv/vulkan.c
