### ISSUE TITLE
can't install games

### ISSUE THREAD

**Issue by basedtho** [varmd/wine-wayland#23]
i've tried about 3-4 different game installers, and i've succeeded with none. it just crashes with

```
0098:err:module:process_init L"C:\\windows\\system32\\explorer.exe" not found
```

how do i run installers with this?

edit: then after some time another error message pops up

```
wl_subsurface@24: error 0: place_above: wl_surface@3 is not a parent or sibling
```

**Comment by varmd** [comment]
GDI apps - e.g installers, popups, etc are not supported. Though the few GOG installers I tried did work.You can extract GOG installers using innoextract. 

>>0098:err:module:process_init L"C:\\windows\\system32\\explorer.exe" not found
This is just a warning message.

>>wl_subsurface@24: error 0: place_above: wl_surface@3 is not a parent or sibling

This is an upstream issue with wlroots - https://github.com/swaywm/wlroots/issues/1865. It works in weston based compositors. One of the reasons why GDI apps are not supported.
