### ISSUE TITLE
Fix Child Window Renderering

### ISSUE THREAD

**Issue by Devorlon** [varmd/wine-wayland#28]
Would it be possible to merge or replicate TKG's child windows patch to fix this [bug](https://bugs.winehq.org/show_bug.cgi?id=45277)?

Looking it over it seems to rely heavily on X11 more specifically adding xcomposite.h.

Or would it be better to bug the Wine team? Because I can understand why you wouldn't want this project to be full of patches.

Thanks

**Comment by varmd** [comment]
Wine-wayland does not support GDI apps besides error popups or simple launchers. The bug is for complex GDI apps. You could try the collabora fork. These may work there.
