### ISSUE TITLE
Upstreaming / collaboration with CodeWeavers?

### ISSUE THREAD

**Issue by shmerl** [varmd/wine-wayland#3]
Did you discuss with CodeWeavers the possibility of upstreaming your work? They seem to be busy with other things, and Wayland is not a priority apparently. So may be your project can speed things up?

**Comment by varmd** [comment]
This is a standalone project, for playing DX/Vulkan games on Wayland without X11. If/when Codeweavers adds Wayland support is upto them.

**Comment by shmerl** [comment]
That wasn't the question really. The question is, whether this effort can be upstreamed. Vulkan games with Wayland is a major use case. So if you are doing it in a way that CodeWeavers can upstream, then why not?

**Comment by Hi-Angel** [comment]
For the record: [upstream bugreport](https://bugs.winehq.org/show_bug.cgi?id=42284)

**Comment by varmd** [comment]
No plans currently

**Comment by mirh** [comment]
https://www.winehq.org/pipermail/wine-devel/2020-December/178575.html
