### ISSUE TITLE
Game Report - Cyberpunk 2077

### ISSUE THREAD

**Issue by pseregiet** [varmd/wine-wayland#31]
Game runs fine for the most part. There are some problems with performance though.

Running the game on ultra gives pretty much the same result as normal wine or proton (20-25 fps on 1440p on my rig). However, as you lower the detail or resolution, the fps rises only to about 45 fps. On normal wine/proton I can get 80+ fps on low settings and very small resolution.
There's also one spot that slows the game to single digits fps. On normal wine/proton this spot is also slowing the game, but not THAT much. This might be caused by the lack of futex2 though. New proton has futex2 enabled and some additional cyberpunk specific patches.

![20210221_15h53m21s_grim](https://user-images.githubusercontent.com/11596839/108628810-2109c100-745d-11eb-921f-d15089372923.png)
![20210221_15h53m31s_grim](https://user-images.githubusercontent.com/11596839/108628815-2830cf00-745d-11eb-8318-6fe587a08b2e.png)
![20210221_15h53m34s_grim](https://user-images.githubusercontent.com/11596839/108628824-2e26b000-745d-11eb-8744-55ed4d06f52d.png)

**Comment by varmd** [comment]
Thanks for the report. I've added the game to the working games list.

futex2 is not supported by wine-wayland, if/unless it is added to the kernel. Otherwise there is little difference with fsync currently and wine-wayland does not support patches outside of mainline wine and fsync/esync.

Regarding resolution, proton uses fshack to change resolutions, which wine-wayland does not support. If this game has resolution scaling you can try that as an alternative to changing resolution.

**Comment by pseregiet** [comment]
Hi. I played in borderless window both on wine and wayland to test how the fps behaves on different resolutions. As far as that goes, there's no problems. But it's like there's some bottleneck, because lowering the details doesn't help. On wine and proton it does. Also, on wine and proton the main menu runs at 200+ fps but on wine-wayland it's 60-70 (my monitor is 144hz).

**Comment by 0933823465** [comment]
#48

**Comment by gardotd426** [comment]
>This might be caused by the lack of futex2 though. New proton has futex2 enabled and some additional cyberpunk specific patches.

Fsync (any variety) actually decreases performance in Cyberpunk 2077 from everything I've seen (and experienced). This isn't unheard of, Fsync is incompatible with some games, it hurts performance in some others.
