### ISSUE TITLE
[Feature request] Multi Monitor identification

### ISSUE THREAD

**Issue by RicArch97** [varmd/wine-wayland#32]
Currently, a resolution is provided in Wineland, however, there is no option to specify on which monitor it should run.

In my case, it chooses to launch games on my side display instead of main, so i have to fully disable that monitor to be able to play.

It would be nice to specify on which monitor the game should run in case there are multiple monitors.

**Comment by ChazyTheBest** [comment]
Usually, this is a decision of the DE. There should be a section in system settings where you can choose how the DE behaves in a multi monitor setup, like open new windows where the current (active) window is, where the cursor is or in a specific monitor, etc.

Now, the sole purpose of this project is to support wine in a wayland environment, not to implement new features or fix existing issues. So, unless it is a wayland specific issue (which I doubt), you should probably report this to [upstream](https://bugs.winehq.org/). For example, you could ask them to add a new option (in winecfg, under graphics) where you can select the preferred monitor (and make it visible only when two or more monitors are detected), which is currently missing.

**Comment by varmd** [comment]
I'm not seeing a way to open a wayland surface on a specific monitor in wayland docs. What you can do is try disabling Wayland fullscreen in Wineland then when the game launches drag the window it to the desired monitor and press F11.
