### ISSUE TITLE
Error Invalid Graphics Configration.

### ISSUE THREAD

**Issue by iMonZ** [varmd/wine-wayland#33]
Hey, I get this error when I try to run Death Stranding:

![image](https://user-images.githubusercontent.com/11319871/111964774-e0997380-8aec-11eb-96d4-f250110dbca4.png)

**Comment by varmd** [comment]
I don't have that game, however it is a D3D12 game. You would need to copy the dll from https://github.com/HansKristian-Work/vkd3d-proton to the game exe directory, then enable the dll in winecfg for the game's WINEPREFIX. I'll add the d3d12 to WINEDLLOVERRIDES in the next release so the last step won't be necessary.

**Comment by iMonZ** [comment]
> I don't have that game, however it is a D3D12 game. You would need to copy the dll from https://github.com/HansKristian-Work/vkd3d-proton to the game exe directory, then enable the dll in winecfg for the game's WINEPREFIX. I'll add the d3d12 to WINEDLLOVERRIDES in the next release so the last step won't be necessary.

Thanks!
Is there a plan for merging this into the wine master repo? (PR)
