### ISSUE TITLE
write: Bad file descriptor

### ISSUE THREAD

**Issue by LowACEy** [varmd/wine-wayland#34]
I tried to follow the steps for Path of Exile. I'm not sure if I missed something in the instructions. For example, I don't have a blue joystick symbol in the launcher. When I start it, it shows `path-of-exile` and Edit and Launch buttons.

The game files are located in `~/.local/share/wineland/path-of-exile/Path of Exile`. When I run `wineland path-of-exile`, I'm getting this log:

```
wine: failed to open L"C:\\windows\\system32\\explorer.exe": c0000135
0024:trace:waylanddrv:process_attach current exe path L"C:\\Path of Exile\\PathOfExileSteam.exe" 
0024:trace:waylanddrv:process_attach current exe L"PathOfExileSteam.exe" 
0024:trace:waylanddrv:WAYLANDDRV_Settings_SetHandlers Resolution settings now handled by: NoRes
0024:trace:waylanddrv:WAYLANDDRV_Settings_SetHandlers Initialized new display modes array
0024:trace:waylanddrv:WAYLANDDRV_CreateWindow L"#32769" 
0024:trace:waylanddrv:WAYLANDDRV_CreateWindow L"Message" 
wine client error:74: write: Bad file descriptor
```

**Comment by varmd** [comment]
Path of Exile was tested with the standalone version from their website. The steam version requires steam for windows which doesn't work reliably.

For the standalone version, you need to install lib32-wine-wayland, download the installer from their website, run it outside wineland using the instructions, then setup a new wineland prefix copy the "Path of Exile" folder to a wineland prefix, edit the exe name in the Edit page and enable GDI option, then start the "Path..." exe and wait for the download to finish. After that, change the exe name to PathOfExile_x64.exe in the wineland Edit page as the 32bit exe won't work. Then click Launch to start the game.

**Comment by LowACEy** [comment]
Thanks!
