### ISSUE TITLE
Additional explanation request

### ISSUE THREAD

**Issue by 1edenec** [varmd/wine-wayland#36]
Hello.
I'm trying to use wine-wayland, but I cannot understand manual.
How can I start game? Manual tells me to copy "gamefolder" to "~/.local/share/wineland/"
But what "gamefolder" means exactly? Is it folder from usual winebottle? Where can I find this folder? Could you add this additional info to manual?

**Comment by varmd** [comment]
Hello,
It is written in the manual - see https://github.com/varmd/wine-wayland#using-wineland-launcher-to-run-games

First you create your-game folder - e.g for Subnautica it would be subnautica. This folder is used as a wrapper folder for dxvk/mangohuds downloads and to launch the game from command line. Then you find YourGameFolder folder - e.g for Subnautica it is called Subnautica and for Civ6 it is SidMeiersCivilizationVI. You can get this folder from EGS, Steam or GOG. All of these have native command line downloaders or installers which do not require 32bit libraries.

Then you copy YourGameFolder into the wrapper folder your-game. So for subnautica you copy/move Subnatica folder to ~/.local/share/wineland/subnatica/ and the final path would be ~/.local/share/wineland/subnatica/Subnautica". Then you modify the settings in the browser and launch the game.

**Comment by 1edenec** [comment]
I read manual, and your explanation, but I stil cannot understand.
In my case, I have download "Baldure's gate III" form GOG.
There are  .exe to install game and files *.bin inside this folder.
I renamed it to balduresgate and put to  ~/.local/share/wineland/
So, now I have game installer inside ~/.local/share/wineland/balduresgate
If I start game with 
`$ wineland balduresgate`
I see 
```
kill: not enough arguments
kill: not enough arguments
Starting balduresgate
/usr/lib/wineland/ui/start.sh: line 56: balduresgate/options.conf: No such file or directorykill:  not enough arguments
kill: not enough arguments
Starting balduresgate
/usr/lib/wineland/ui/start.sh: line 56: balduresgate/options.conf: No such file or directory
```
I also tried to put this game files to 
~/.local/share/wineland/balduresgate/balduresgate
same result.
