### ISSUE TITLE
It seems like you tested FL Studio, can you please confirm if this issue happens on your side?

### ISSUE THREAD

**Issue by pushqrdx** [varmd/wine-wayland#43]
Sorry for opening an issue for this but i want to make sure that this doesn't happen only on my side.
Is resizing the mixer window glitchy, it flickers and slow? the rest of the UI is fine and smooth except this issue

**Comment by distek** [comment]
This has been an issue for for as long a I can remember. I recently tried FL on windows and noticed that it's a lot less glitchy but still relatively slow/choppy compared to the rest of the UI. Not sure there's much to be done on the wine side of things without someone targeting FL directly.

**Comment by pushqrdx** [comment]
at least the issue where there's weird Square characters next to each mixer slot name is fixable by copying `Windows\Fonts` from a windows install to the wine prefix
