### ISSUE TITLE
Question: will be wine3d wrapper supported at some point?

### ISSUE THREAD

**Issue by neofeo** [varmd/wine-wayland#44]
Hi, very interested on this project. The thing is, I test wine over box86 on arm linux platforms like rpi4 or rk3399. The first one have a vulkan driver but doesn't have the features for dxvk. I wonder if there is any chance to get wine3d to work with wayland bc the opengl performance on rpi4 under x11 its 3.5 times lower than over wayland. For panfrost (rk3399, etc) dxvk may have a chance,  but there is no conformant driver so far.

For wine 64 bit like the one available here we use box64.

**Comment by varmd** [comment]
Only vulkan is supported and wined3d is much slower and buggier than DXVK.
