### ISSUE TITLE
Proton file

### ISSUE THREAD

**Issue by DeeBeeDouble** [varmd/wine-wayland#45]
Would it be possible to create a simple proton file (like proton ge does) which you can put in the compatibilitytools.d folder and then select in steam? It would be way easier, and it would allow drm games which need to be launched through steam to work. I don't know, maybe that's not possible but would be cool if it works ;) 

Have a nice day everyone!

**Comment by varmd** [comment]
Steam currently requires X11 libs, Xwayland and a huge number of 32bit libs. So it makes using this project pointless.

You can download games from Steam using steamctl (https://github.com/ValvePython/steamctl) - or its ui - https://github.com/dmadisetti/steam-tui
