### ISSUE TITLE
`could not load kernel32.dll` after installing `lib32-wine-wayland`

### ISSUE THREAD

**Issue by mizzunet** [varmd/wine-wayland#49]
I'm getting,
```
wine: could not load kernel32.dll, status c0000135
```
for anything program and even `winecfg`.

Persists before and after exporting the following as README suggests,
```
export LD_LIBRARY_PATH="/usr/lib/wineland/lib32:$LD_LIBRARY_PATH" 
export VK_ICD_FILENAMES="/usr/lib/wineland/vulkan/icd.d/intel_icd.i686.json:/usr/lib/wineland/vulkan/icd.d/radeon_icd.i686.json" 
```

Though, these programs working fine with the standard `wine-stable` which also installs some `lib32` stuff

**Comment by varmd** [comment]
Probably a conflict with lib32 stuff installed by wine-stable. And lib32-wine-wayland also requires wine-wayland.

**Comment by mizzunet** [comment]
So, any workaround can you suggest?

**Comment by YusufKhan-gamedev** [comment]
> So, any workaround can you suggest?

Not using wine-stable

**Comment by Teabagisking** [comment]
how do i do that

**Comment by varmd** [comment]
You can use wineland to run games without installing anything. For apps you are better off with regular wine.
