### ISSUE TITLE
No driver could be loaded

### ISSUE THREAD

**Issue by codeclem** [varmd/wine-wayland#51]
I created `.local/share/wineland/path-of-exile` and coped the game folder from my windows partition so it looks like `.local/share/wineland/path-of-exile/PathOfExile/PathOfExile_x64.exe` Then I pointed the launcher to that exe, and when I run `wineland path-of-exile` it downloaded dxvk, vkd3d, and wine and gives this error:

```
00f8:err:module:open_builtin_so_file failed to load .so lib "/usr/lib32/wine/i386-unix/winewayland.drv.so"
00f8:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
```

This is on an AMD machine using integrated Ryzen graphics and sway, with mesa and vulkan-radeon drivers. This error only happens on the first time I try lauching the game, subsequent attempts give no error but nothing happens

```
$ wineland path-of-exile
Starting path-of-exile

64bit game

Launching path-of-exile
$ 
```

**Comment by varmd** [comment]
PathOFExile is a 64bit game. IIRC it only runs with a launcher. You can change the exe in the settings, and enable GDI windows to so it can download the updates. Then click Launch. You may also need to check that mesa Vulkan is working in wayland and also change DirectX11 to Vulkan in the game's text settings - if it doesn't launch with DX11.
