### ISSUE TITLE
wineland only install 32-bit version of wine

### ISSUE THREAD

**Issue by Jonathonfidiam** [varmd/wine-wayland#57]
Is there an issue with using symlinks instead of just copying over the game files to my home directory? I don't have a large hard drive for my OS drive and have my games on all other HDDs.   I am getting an error about wine only being 32-bit for every application I try to run thru wineland

**Comment by varmd** [comment]
Symlinks should work. The other error is probably due to missing main wine-wayland package, which also needs to be installed if lib32-wine-wayland is installed.
