### ISSUE TITLE
is there a way to use wine-wayland without Arch?

### ISSUE THREAD

**Issue by apprehensions** [varmd/wine-wayland#62]
alternatively, is there a way to compile this without makepkg or Arch utilities? i am on an distro that isn't based on Arch.

**Comment by milkknife** [comment]
I got wine to work on wayland without wine-wayland by forcing lutris flatpak to wayland-only, and installing the `glfw-wayland` package. You can check which processes are running on xwayland using `xlsclients`. It might be better to try that out as wine-wayland is basically unmaintained ie. most pull requests and issues have been untouched for months.

**Comment by wael444** [comment]
https://gitlab.collabora.com/alf/wine

is this technically what this repository is based off of?

**Comment by lavilao** [comment]
> https://gitlab.collabora.com/alf/wine
> 
> is this technically what this repository is based off of?

I dont think so given that this was developed before the collabora version and is vulkan-only.

**Comment by varmd** [comment]
You could try Conty or junest. Or try compiling collabora's wine-wayland for your distro.
