### ISSUE TITLE
System wine not detected after installing arch package

### ISSUE THREAD

**Issue by restfuladi** [varmd/wine-wayland#63]
I'd like to use this with Lutris but it's not showing up in the runners list, is it possible to add it manually? Thanks.

edit: added /sbin/wine64 manually and it kind of works. No mouse or keyboard input but somehow the xbox one controller works. It also gets confused by my 2x display scale setting and shows only the upper left quadrant of the game window.

**Comment by varmd** [comment]
This has its own launcher wineland. The latest version also has a portable mode, which may work with Lutris.

For the other issues a separate issue with more details is needed.
