### ISSUE TITLE
Invisible window

### ISSUE THREAD

**Issue by Henry-Hiles** [varmd/wine-wayland#64]
Upon running any application with wine-wayland, (using Notepad++ to test), it opens as a completely transparent window, which will not close without killing it. Also, `export WINE_VK_VULKAN_ONLY=1` causes nothing to open at all. Any help would be appreciated, thank you.

**Comment by Henry-Hiles** [comment]
I am using this command to run: `WINEDLLOVERRIDES="dxgi,d3d11=n,b;dinput=d;winedbg=d;winemenubuilder.exe=d;mscoree=d;mshtml
=d" wine64 Downloads/npp.exe`, and have this output: 
```
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
0074:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0074:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0074:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0074:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00c8:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
00c8:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
00c8:err:ole:apartment_get_local_server_stream Failed: 0x80004002
00c8:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000000000): stub
00c0:fixme:imm:ImmReleaseContext (00010050, 00000000): stub
^C00e0:fixme:console:default_ctrl_handler Terminating process bc on event 0
```

**Comment by Henry-Hiles** [comment]
The window looks like this: 
![image](https://user-images.githubusercontent.com/71790868/213934487-7bd5bffc-ec5a-4af5-b966-96b77c9f4006.png)

**Comment by Henry-Hiles** [comment]
I am on the Hyprland compositor.

**Comment by varmd** [comment]
Wine-wayland does not support GDI apps such as Notepad++, although popups or simple launchers should work. 

You can use nppnext as Notepad++ replacement, or collabora's wine-wayland if you really need Notepad++. Although in my experience Notepad++ is slower on Linux.

**Comment by Henry-Hiles** [comment]
Oh I see, so games like rocket league and roblox should work?
