### ISSUE TITLE
Test report - Nvidia, KDE Wayland

### ISSUE THREAD

**Issue by Deytron** [varmd/wine-wayland#65]
Here's some testing I did with one game.

## Environment

OS: EndeavourOS Linux x86_64 
Host: MS-7C52 1.0 
Kernel: 6.1.8-arch1-1 
Uptime: 41 mins 
Packages: 1501 (pacman), 10 (flatpak) 
Shell: zsh 5.9 
Resolution: 1920x1080 
DE: Plasma 5.26.5 
WM: kwin 
Theme: [Plasma], Layan [GTK2/3] 
Icons: [Plasma], Tela [GTK2/3] 
Terminal: yakuake 
CPU: AMD Ryzen 5 3600X (12) @ 4.000GHz 
GPU: NVIDIA GeForce RTX 2060 Rev. A 
Memory: 4968MiB / 32045MiB 

**Game tested :** Civilization VI Gathering Storm (latest version, DX11)

_Test was done with Lutris by selecting the custom wine64 binaries_

## Results

- Game starts properly, gets to main menu. It it quite laggy, maybe due to shaders ?
- Sound working (pipewire)
- Keyboard and mouse not working : 

  - System cursor cannot click on anything
  - Pressing F9/F10 makes the cursor disappear
  - Using `WINE_VK_USE_CUSTOM_CURSORS=1` makes the game cursor appears, but still can't click on anything
  - Using `WINE_VK_VULKAN_ONLY=1` is the same as above
  - Repeatedly pressing F9/F10 crashes the game with `error 1`

**Comment by varmd** [comment]
This looks like it's missing patches for Civ6. You could try another Release or this one - https://github.com/varmd/wine-wayland/releases/tag/v6.10.0 - that worked with Civ6.
