### ISSUE TITLE
FreeBSD

### ISSUE THREAD

**Issue by elgithubo** [varmd/wine-wayland#69]
When trying to build on FreeBSD I receive the following message:
```
elgrande@elfreebsdo ~/g/wine-wayland (master)> makepkg
/usr/local/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf-8): No such file or directory
==> ERROR: wine-wayland is not available for the 'amd64' architecture.
```
Any hint how I can build on FreeBSD?

**Comment by lostybtw** [comment]
Hi, So it appears you are using makepkg and in that case you may need to tweak the PKGBUILD 
You'd need to use '-m32' in CFLAGS and CXXFLAGS and change the PKGCONFIG_PATH to '/usr/lib32/(whatever)'

[https://wiki.archlinux.org/title/32-bit_package_guidelines](url)

And try using regular make compiling if it isn't fixed, with the same flags.

**Comment by lostybtw** [comment]
Please Mark this as resolved.

**Comment by elgithubo** [comment]
I will, sorry for being currently indisponible.

**Comment by elgithubo** [comment]
Since I have no requirement for compiling this project anymore, I am closing this issue.
