### ISSUE TITLE
Add OpenGL Support

### ISSUE THREAD

**Issue by steven-gg** [varmd/wine-wayland#9]
That is much needed for OpenGL only graphic adapters, as they are still in use.

**Comment by varmd** [comment]
No plans to support OpenGL. Most GPUs today support Vulkan and games on Linux run better on Vulkan.

**Comment by toby63** [comment]
For those searching for a solution, you might take a look at this:
https://docs.mesa3d.org/gallium/drivers/zink.html

I don't know though, what the status of this is exactly.
The two important points are:
1. What GPUs are supported 
2. What OpenGL versions are supported

For usage instructions I only found this:
https://gitlab.freedesktop.org/kusma/mesa/-/wikis/zink-building-and-running
